import type { ReactNode, FC, ReactElement } from "react";
import type { Metadata } from "next";
import "@/styles/index.css";

interface Props {
    children: ReactNode;
}

export const metadata: Metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

const RootLayout: FC<Props> = ({ children }): ReactElement => {
    return (
        <html lang="en" dir="ltr">
            <body className="bg-neutral-900 text-white">
                { children }
            </body>
        </html>
    );
}

export default RootLayout;